In [10]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import torch 
import pandas as pd 
import numpy as np 
from torch.utils.data import TensorDataset,DataLoader

In [2]:
train_adress = 'D:/google_download/all/train.csv'
train = pd.read_csv(train_adress)
print(train.head())

                    qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [3]:
train = train[['question_text','target']]

#定义好相关的API 
tokenizer = Tokenizer(num_words = 100000)
#API对数据的适应
tokenizer.fit_on_texts(list(train['question_text']))
train_x = tokenizer.texts_to_sequences(train['question_text'])
train_x = pad_sequences(train_x,maxlen=40,padding='post')

In [4]:
train_x[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    9,   48, 6683, 7219,  158,   55,
       6107,   36,    4, 1206,    6,    1, 8333])

In [5]:
encoded_label = np.array(train['target'])

In [6]:
split_frac = 0.8
split_idx = int(len(train_x) * split_frac)

train_x , remainding_x = train_x[:split_idx] , train_x[split_idx:]
train_y , remainding_y = encoded_label[:split_idx] , encoded_label[split_idx:]

In [7]:
val_frac = 0.1
val_split = int(len(remainding_x) * val_frac)

val_x , test_x = remainding_x[:val_split] , remainding_x[val_split:]
val_y , test_y = remainding_y[:val_split] , remainding_y[val_split:]

In [8]:
train_x = np.array(train_x)
val_x = np.array(val_x)
test_x = np.array(test_x)
print(train_x[0])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    9   48 6683
 7219  158   55 6107   36    4 1206    6    1 8333]


In [11]:
train_data = TensorDataset(torch.from_numpy(train_x),torch.from_numpy(train_y))
val_data  = TensorDataset(torch.from_numpy(val_x),torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x),torch.from_numpy(test_y))

In [12]:
batch_size = 50 
train_loader = DataLoader(train_data,shuffle= True , batch_size = batch_size)
val_loader = DataLoader(val_data,shuffle= True ,batch_size = batch_size)
test_loader = DataLoader(test_data,shuffle= True ,batch_size = batch_size)

In [13]:
dataiter = iter(train_loader)
sample_x ,sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([50, 40])
Sample input: 
 tensor([[     0,      0,      0,  ...,      1,   1160,   5017],
        [     0,      0,      0,  ...,    950,     10,     16],
        [     0,      0,      0,  ...,     70,    257,    245],
        ...,
        [     0,      0,      0,  ...,    297,     10,   2187],
        [     0,      0,      0,  ...,      1,    142,     99],
        [     0,      0,      0,  ...,    114,  30228,  23091]], dtype=torch.int32)

Sample label size:  torch.Size([50])
Sample label: 
 tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  1,  0,  0])
